apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-web
  template:
    metadata:
      labels:
        app: library-web
    spec:
      containers:
        - name: library-web
          image: umer055/my-web-app
          ports:
            - containerPort: 3000

